# Storage Class definition
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-opensdsplugin
provisioner: csi-opensdsplugin
parameters:
  fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-opensdsplugin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-sc-opensdsplugin

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: xxwjj/wordpress:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: wordpress
          containerPort: 8081
        volumeMounts:
          - mountPath: /mnt/wordpress
            name: csi-data-opensdsplugin
      volumes:
        - name: csi-data-opensdsplugin
          persistentVolumeClaim:
            claimName: csi-pvc-opensdsplugin
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  ports:
  - name: wordpress
    port: 8081
    targetPort: 8081
    nodePort: 32081
    protocol: TCP
  selector:
    app: wordpress
